### ISSUE TITLE
Npm run start => error on fresh setup

### ISSUE THREAD

**Issue by ghn** [liip/django-template#54]
Fresh setup gives the following error when running `npm run start`

> (ENV) vagrant@capstone:/vagrant$ npm start
> 
> > capstone@1.0.0 start /vagrant
> > NODE_ENV=development webpack-dev-server --hot
> 
> /vagrant/node_modules/webpack-cli/bin/config-yargs.js:89
> 				describe: optionsSchema.definitions.output.properties.path.description,
> 				                                           ^
> 
> TypeError: Cannot read property 'properties' of undefined
>     at module.exports (/vagrant/node_modules/webpack-cli/bin/config-yargs.js:89:48)
>     at Object.<anonymous> (/vagrant/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:40)
>     at Module._compile (module.js:653:30)
>     at Object.Module._extensions..js (module.js:664:10)
>     at Module.load (module.js:566:32)
>     at tryModuleLoad (module.js:506:12)
>     at Function.Module._load (module.js:498:3)
>     at Function.Module.runMain (module.js:694:10)
>     at startup (bootstrap_node.js:204:16)
>     at bootstrap_node.js:625:3
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! capstone@1.0.0 start: `NODE_ENV=development webpack-dev-server --hot`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the capstone@1.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/vagrant/.npm/_logs/2018-10-29T21_24_36_244Z-debug.log

Upgrade `webpack-cli` to latest version fixes the problem, but then no assets is served correctly (404 on .css and .js). I've no time for more investigation atm.

**Comment by sephii** [comment]
I don't think that's related to the django-template. See https://github.com/liip/drifter/issues/230 for a fix.

**Comment by ghn** [comment]
Ok first webpack bug is totally related to drifter role.

Though, even when webpack transpiles correctly (and outputs "webpack output is served from /static/") the main page "it works" has no css nor js files. The generated urls lead to a 404 in both case.

I only followed what is explained in README file.

**Comment by sephii** [comment]
Ah sorry I haven't read properly until the end. I'll try to reproduce and let you know.

**Comment by ghn** [comment]
I did more testing. Django routes the right folder `/static/dist`. Again, it's a problem with webpack not creating the files (or not injecting them). I'll dig a bit further
