### ISSUE TITLE
Improvement: Have a test database ready with fixtures

### ISSUE THREAD

**Issue by ghn** [liip/django-template#67]
It's be nice the django-template proposes a way to quickly create fixtures for the tests + have a separated test database.

**Comment by sephii** [comment]
The test database is something we already have since [Django does it by default](https://docs.djangoproject.com/en/2.1/topics/testing/overview/#the-test-database). For the fixtures I think adding `factory-boy` to the test requirements would be enough, or did you have anything else in mind?

**Comment by ghn** [comment]
Well yes I agree. That's what we ended up with for last project. My point was more: we have a set of fixtures for DEV, it'd be nice to load this whole set on TEST sometimes. I'll figure out something
