### ISSUE TITLE
Improvement: Env vars

### ISSUE THREAD

**Issue by ghn** [liip/django-template#68]
Document or improve scrirpt for creating/updating environment variable

**Comment by sephii** [comment]
You're talking about manually setting an environment variable on the remote server, right? We already have a [`set_setting`](https://github.com/liip/django-template/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/fabfile.py#L178) function in the fabfile, we could just add a @task decorator so we can use in manually. What do you think?
